# Issue Labeler Configuration for Manuscript Programming Language

# Bug reports
bug:
  - '(bug|error|issue|problem|broken|fail|crash|exception)'
  - '(not working|doesn''t work|does not work)'
  - '(unexpected behavior|incorrect|wrong)'

# Feature requests
enhancement:
  - '(feature|enhancement|improvement|suggestion)'
  - '(add|implement|support|would like|wish|want)'
  - '(new feature|feature request)'

# Documentation related
documentation:
  - '(doc|docs|documentation|readme|guide|tutorial)'
  - '(example|examples|sample)'
  - 'docs/'
  - 'README'
  - '(typo|spelling|grammar)'

# Language features and grammar
language:
  - '(grammar|syntax|parser|lexer|ast)'
  - '(language feature|language construct)'
  - '(keyword|operator|expression)'
  - 'internal/grammar'
  - 'internal/parser'
  - 'internal/ast'

# Compiler and transpiler
compiler:
  - '(compiler|compilation|transpiler|transpilation)'
  - '(code generation|codegen|generate)'
  - 'internal/compile'
  - 'visitors/go-transpiler'

# Standard library
stdlib:
  - '(stdlib|standard library|builtin|builtins)'
  - 'stdlib/'
  - 'internal/builtins'

# Testing
testing:
  - '(test|testing|spec|coverage)'
  - 'tests/'
  - '(unit test|integration test)'

# Performance
performance:
  - '(performance|speed|slow|fast|optimization|optimize)'
  - '(memory|cpu|benchmark)'

# CLI and tooling
cli:
  - '(cli|command line|tool|binary)'
  - 'cmd/'
  - '(flag|argument|option)'

# Editor support
editor:
  - '(editor|vscode|syntax highlighting|lsp)'
  - 'manuscript-vscode-extension'
  - 'publish/lsp'
  - '(intellisense|autocomplete|completion)'

# Configuration
config:
  - '(config|configuration|settings)'
  - 'internal/config'
  - '(yaml|yml|json|toml)'

# Build and CI/CD
build:
  - '(build|ci|cd|github actions|workflow)'
  - 'Makefile'
  - '\.github/'
  - '(docker|container)'

# Good first issue (for newcomers)
"good first issue":
  - '(good first issue|beginner|easy|starter)'
  - '(newcomer|first contribution)'

# Help wanted
"help wanted":
  - '(help wanted|help needed|assistance)'
  - '(looking for help|need help)'

# Question
question:
  - '(question|how to|how do|help)'
  - '\?'
  - '(confused|unclear|understand)'

# Duplicate
duplicate:
  - '(duplicate|already reported|same as)'

# Invalid
invalid:
  - '(invalid|not a bug|not an issue)'
  - '(user error|misunderstanding)'

# Priority labels
"priority/high":
  - '(urgent|critical|high priority|blocker)'
  - '(security|vulnerability)'

"priority/medium":
  - '(medium priority|important)'

"priority/low":
  - '(low priority|nice to have|minor)' 