# Issue Labeler Configuration for Manuscript Programming Language

# Bug reports
bug:
  - '(?i)(bug|error|issue|problem|broken|fail|crash|exception)'
  - '(?i)(not working|doesn''t work|does not work)'
  - '(?i)(unexpected behavior|incorrect|wrong)'

# Feature requests
enhancement:
  - '(?i)(feature|enhancement|improvement|suggestion)'
  - '(?i)(add|implement|support|would like|wish|want)'
  - '(?i)(new feature|feature request)'

# Documentation related
documentation:
  - '(?i)(doc|docs|documentation|readme|guide|tutorial)'
  - '(?i)(example|examples|sample)'
  - '(?i)docs/'
  - '(?i)README'
  - '(?i)(typo|spelling|grammar)'

# Language features and grammar
language:
  - '(?i)(grammar|syntax|parser|lexer|ast)'
  - '(?i)(language feature|language construct)'
  - '(?i)(keyword|operator|expression)'
  - '(?i)internal/grammar'
  - '(?i)internal/parser'
  - '(?i)internal/ast'

# Compiler and transpiler
compiler:
  - '(?i)(compiler|compilation|transpiler|transpilation)'
  - '(?i)(code generation|codegen|generate)'
  - '(?i)internal/compile'
  - '(?i)visitors/go-transpiler'

# Standard library
stdlib:
  - '(?i)(stdlib|standard library|builtin|builtins)'
  - '(?i)stdlib/'
  - '(?i)internal/builtins'

# Testing
testing:
  - '(?i)(test|testing|spec|coverage)'
  - '(?i)tests/'
  - '(?i)(unit test|integration test)'

# Performance
performance:
  - '(?i)(performance|speed|slow|fast|optimization|optimize)'
  - '(?i)(memory|cpu|benchmark)'

# CLI and tooling
cli:
  - '(?i)(cli|command line|tool|binary)'
  - '(?i)cmd/'
  - '(?i)(flag|argument|option)'

# Editor support
editor:
  - '(?i)(editor|vscode|syntax highlighting|lsp)'
  - '(?i)manuscript-vscode-extension'
  - '(?i)publish/lsp'
  - '(?i)(intellisense|autocomplete|completion)'

# Configuration
config:
  - '(?i)(config|configuration|settings)'
  - '(?i)internal/config'
  - '(?i)(yaml|yml|json|toml)'

# Build and CI/CD
build:
  - '(?i)(build|ci|cd|github actions|workflow)'
  - '(?i)Makefile'
  - '(?i)\.github/'
  - '(?i)(docker|container)'

# Good first issue (for newcomers)
"good first issue":
  - '(?i)(good first issue|beginner|easy|starter)'
  - '(?i)(newcomer|first contribution)'

# Help wanted
"help wanted":
  - '(?i)(help wanted|help needed|assistance)'
  - '(?i)(looking for help|need help)'

# Question
question:
  - '(?i)(question|how to|how do|help)'
  - '(?i)\?'
  - '(?i)(confused|unclear|understand)'

# Duplicate
duplicate:
  - '(?i)(duplicate|already reported|same as)'

# Invalid
invalid:
  - '(?i)(invalid|not a bug|not an issue)'
  - '(?i)(user error|misunderstanding)'

# Priority labels
"priority/high":
  - '(?i)(urgent|critical|high priority|blocker)'
  - '(?i)(security|vulnerability)'

"priority/medium":
  - '(?i)(medium priority|important)'

"priority/low":
  - '(?i)(low priority|nice to have|minor)' 