# theme.toml template for a Hugo theme
name = "Manuscript"
license = "MIT"
licenselink = "https://github.com/manuscript-co/manuscript/blob/main/LICENSE"
description = "A simple, clean theme for the Manuscript programming language documentation"
homepage = "https://manuscript-lang.dev"
min_version = "0.100.0"

[author]
  name = "Manuscript Team"
  homepage = "https://github.com/manuscript-co/manuscript" 