name: Issue Labeler

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Label issues based on content
        id: labeler
        uses: hoho4190/issue-pr-labeler@v2.0.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          config-file-name: labeler-config.yml
      - name: Show labeling results
        if: always()
        run: |
          echo "=== Issue Labeler Results ==="
          echo "Action completed successfully"
          echo "=== End Results ===" 